### ISSUE TITLE
Support other sources in templated env vars

### ISSUE THREAD

**Issue by chunter0** [solo-io/skv2#565]
Would like to be able to template env values pull from different sources (e.g: ConfigMap, Secret)

```yaml
        env:
          - name: USERNAME
            valueFrom: 
              secretKeyRef:
                key: '{{ $.Values.usernameKey }}'
                name: '{{ $.Values.someSecret }}' 
          - name: PASSWORD
            valueFrom: 
              configMapKeyRef:
                key: '{{ $.Values.passwordKey }}'
                name: '{{ $.Values.someConfigMap }}'
```
